services:
  caddy:
    extends:
      file: ./services/caddy/docker-compose.yml
      service: caddy

  vaultwarden:
    extends:
      file: ./services/vaultwarden/docker-compose.yml
      service: vaultwarden

  immich-server:
    extends:
      file: ./services/immich/docker-compose.yml
      service: immich-server

  immich-machine-learning:
    extends:
      file: ./services/immich/docker-compose.yml
      service: immich-machine-learning

  immich-postgres:
    extends:
      file: ./services/immich/docker-compose.yml
      service: immich-postgres

  immich-redis:
    extends:
      file: ./services/immich/docker-compose.yml
      service: immich-redis

networks:
  homelab:
    driver: bridge

volumes:
  caddy_data:
  caddy_config: